# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class AwsSts < Formula
  desc "Install tools"
  homepage "https://github.com/oals-dev/homebrew-tap"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oals-dev/aws-sts/releases/download/v0.1.3/aws-sts_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "84d6ab4e510c2d07280e1a2559faa1dc3eb0adc696547ac7b6036731325aee8e"

      def install
        bin.install "aws-sts"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oals-dev/aws-sts/releases/download/v0.1.3/aws-sts_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "42a75d3408cc26c848d21cd98a91942384bfc1468419e3ae96021a25bb4a87d4"

      def install
        bin.install "aws-sts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oals-dev/aws-sts/releases/download/v0.1.3/aws-sts_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9dc6775f31e862c69e887785300f1c03878c9df45200a3c01441796409ee8119"

      def install
        bin.install "aws-sts"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oals-dev/aws-sts/releases/download/v0.1.3/aws-sts_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "38e3e981a24c97160f8756b616de8a9450298375c3e90bafe1e4b71142ce12bd"

      def install
        bin.install "aws-sts"
      end
    end
  end

  test do
    system "#{bin}/aws-sts -v"
  end
end
