# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class AwsSts < Formula
  desc "Install tools"
  homepage "https://github.com/oals-dev/homebrew-tap"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oals-dev/aws-sts/releases/download/v0.0.6/aws-sts_0.0.6_Darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a0d5aa8701bdf704ba888228a7f0a851587f7ed8d6c20806a4b99260fb707268"

      def install
        bin.install "aws-sts"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oals-dev/aws-sts/releases/download/v0.0.6/aws-sts_0.0.6_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "afcbb4c2f447033838499de7229b9c94dda1997956e6ff836e523dea9af4025a"

      def install
        bin.install "aws-sts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oals-dev/aws-sts/releases/download/v0.0.6/aws-sts_0.0.6_Linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ce863b6d0c04285e67f09a43c39aa0473760b3010d35f56203b25b9217ddca0c"

      def install
        bin.install "aws-sts"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oals-dev/aws-sts/releases/download/v0.0.6/aws-sts_0.0.6_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e6e29670788f69efa65b6ed7d16f554d627628e56cfae96d089c031f8f8d0bef"

      def install
        bin.install "aws-sts"
      end
    end
  end

  test do
    system "#{bin}/aws-sts -v"
  end
end
