# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class AwsSts < Formula
  desc "Install tools"
  homepage "https://github.com/oals-dev/homebrew-tap"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/oals-dev/aws-sts/releases/download/v0.1.1/aws-sts_0.1.1_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3d03a8fbd73841cd5b53fa3aadff77739c2e0e3a860bd5f8ffad77e8d549a12d"

      def install
        bin.install "aws-sts"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oals-dev/aws-sts/releases/download/v0.1.1/aws-sts_0.1.1_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "66801e35bce94450b77da44a57bb9c1940c2434c7ef9b99164f8ae8a3032c5dd"

      def install
        bin.install "aws-sts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oals-dev/aws-sts/releases/download/v0.1.1/aws-sts_0.1.1_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e8620991df6ae0fe242a6a46c693064460f0a776a170fdfdfcf12f7a67748342"

      def install
        bin.install "aws-sts"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/oals-dev/aws-sts/releases/download/v0.1.1/aws-sts_0.1.1_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "651f239b317bb36bdcb26047adbb5a40bc31f6ea5e812df305ca18da3c09ab3d"

      def install
        bin.install "aws-sts"
      end
    end
  end

  test do
    system "#{bin}/aws-sts -v"
  end
end
